# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0004_auto_20181024_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessFailureLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Username')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Attempt Time')),
                ('failures', models.PositiveIntegerField(verbose_name='Total Failed Logins')),
            ],
            options={
                'ordering': ['-attempt_time'],
                'verbose_name': 'user access failure log',
                'verbose_name_plural': 'user access failure logs',
            },
        ),
    ]
