# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0005_useraccessfailurelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccessfailurelog',
            name='failures',
            field=models.PositiveIntegerField(default=1, verbose_name='Total Failed Logins'),
        ),
    ]
