# Generated by Django 4.2.5 on 2023-09-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("axes", "0008_accessfailurelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessattempt",
            name="attempt_time",
            field=models.DateTimeField(verbose_name="Attempt Time"),
        ),
        migrations.AlterField(
            model_name="accessfailurelog",
            name="attempt_time",
            field=models.DateTimeField(verbose_name="Attempt Time"),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="attempt_time",
            field=models.DateTimeField(verbose_name="Attempt Time"),
        ),
    ]
