# Generated by Django 4.2.21 on 2025-05-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0009_add_session_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessattempt',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='The time when this access attempt expires and is no longer valid.', null=True, verbose_name='Expires At'),
        ),
    ]
