# Generated by Django 5.2.1 on 2025-06-07 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axes", "0009_add_session_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessAttemptExpiration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time when access attempt expires and is no longer valid.",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "access_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiration",
                        to="axes.accessattempt",
                        verbose_name="Access Attempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "access attempt expiration",
                "verbose_name_plural": "access attempt expirations",
            },
        ),
    ]
